### ISSUE TITLE
Allow for specific ordering of events

### ISSUE THREAD

**Issue by krainboltgreene** [hauleth/plug_telemetry_server_timing#5]
So here's my output:

![Screen Shot 2020-11-04 at 3 06 47 PM](https://user-images.githubusercontent.com/334809/98177446-80909080-1eaf-11eb-8311-24eabdadc79f.png)

While you can't tell, its:

  - query decode time
  - query idle time
  - query query time
  - query queue time
  - query total time
  - endpoint stop duration

However my install code looks like this:

``` elixir
    Plug.Telemetry.ServerTiming.install([
      {[:phoenix, :endpoint, :stop], :duration},
      {[:database, :repository, :query], :total_time},
      {[:database, :repository, :query], :decode_time},
      {[:database, :repository, :query], :query_time},
      {[:database, :repository, :query], :queue_time},
      {[:database, :repository, :query], :idle_time}
    ])
```

How are these orders so different?

**Comment by hauleth** [comment]
Current ordering depends on the order in which events happened in the application, not on the order of the events in the `install/1` call. Reason for that is that in future I want to support `total` when w3c/server-timing#44 will land. Ordering events in the user-provided way may then be confusing default.

**Comment by krainboltgreene** [comment]
Oof, that's a rough problem, I can understand your hesitation.
