### ISSUE TITLE
Issue booting with plug

### ISSUE THREAD

**Issue by krainboltgreene** [hauleth/plug_telemetry_server_timing#8]
```
Unchecked dependencies for environment dev:
* plug_telemetry_server_timing (Hex package)
  the dependency does not match the requirement "~> 0.2.0", got "0.0.0-dev"
** (Mix) Can't continue due to errors on dependencies
```

I don't really understand what's going on here?

**Comment by krainboltgreene** [comment]
I think it's because of

https://github.com/hauleth/plug_telemetry_server_timing/blob/master/mix.exs#L58-L64

Because the key is a string, not an atom.

That said, why is this code doing this?

**Comment by hauleth** [comment]
Uh, ok, I need to check that out.

The code is to easy maintenance to reuse Git tags as a source of truth for managing the project versioning, in similar vain the `{vsn, git}` works in the Rebar3.

In short, it tries to fetch version from Hex metadata (if present) or from Git (via `git describe`). If both method failed then it will fall back to `"0.0.0-dev"`.

I will update that soon.

**Comment by hauleth** [comment]
Release 0.2.1 is coming in a moment. I will retract 0.2.0 from Hex afterwards.

**Comment by hauleth** [comment]
Of course I have screwed with 0.2.1 so I needed to release 0.2.2. Now it is all fixed and working. Sorry for the trouble.

**Comment by krainboltgreene** [comment]
I appreciate the hard work, thanks for the patches <3

FWIW I think regardless the next release should be 1.0.0. It's already a very useful library and has only gotten more useful.
